# Generated by Django 3.0.4 on 2020-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='relateapi',
            new_name='api',
        ),
    ]
