# Generated by Django 3.0.4 on 2020-05-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstproj', '0003_auto_20200511_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='fail_case',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='fail_step',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='succees_case',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='succees_step',
        ),
    ]
